### ISSUE TITLE
negative zero is not equal to positive zero

### ISSUE THREAD

**Issue by maxbla** [rust-num/num-bigint#100]
Although I don't know of a way to get negative zero (i.e. `BigInt{Sign::Minus data:BigUint::zero()}`), besides my first attempt at an implementation of `Arbitrary`, negative zero should equal positive zero, as it does with floats. Maybe we could also throw in a panic if in debug mode.

**Comment by cuviper** [comment]
That shouldn't be possible -- if the sign is `Plus` or `Minus`, it should have non-zero `data`. The `data` should also be free of trailing zeros, so its last digit always has the most significant bit.
