### ISSUE TITLE
How to create bigint from big literal?

### ISSUE THREAD

**Issue by pebble8888** [rust-num/num-bigint#112]
I want to create a BigInt for 1855425871872000000000.
I have to use this.

let c = ((BigInt::from(1855425) * BigInt::from(1000000) + BigInt::from(871872))) * BigInt::from(1000000000);

Any better way exists?

**Comment by cuviper** [comment]
`BigInt::from` is the easiest, if you have a literal which fits in one of the primitive types. Note that unspecified literal integers default to `i32` if type inference doesn't lead elsewhere, which isn't enough here. Your example is a 71-bit number, so you could use `i128` or `u128`.

```rust
let c = BigInt::from(1855425871872000000000_u128);
```

For numbers larger than 128 bits, parsing a string is probably the easiest to read. You can also specify the number in `u32` digits with `BigInt::new` or `from_slice`, or use any of the other available digits: `from_bytes_le`/`be`, `from_signed_bytes_le`/`be`, `from_radix_le`/`be`.

**Comment by pebble8888** [comment]
I'm really thankfull to you.
I didn't know BigInt support i128,u128.
I need a number larger than 128 bit.
So I wrote this.
``` rust
let g = BigInt::from(1_000_000_000_000_000_000_000_000_000_000_000_000_i128);
let a = 
BigInt::from(123_123_123_123_123_123_123_123_123_123_123_123_i128) * g.power(2)
+ BigInt::from(123_123_123_123_123_123_123_123_123_123_123_123_i128) * g.power(1)
+ BigInt::from(123_123_123_123_123_123_123_123_123_123_123_123_i128);
```
