### ISSUE TITLE
doc nit: to_u32_digits doc uses "little-endian order" instead of "least significant first"

### ISSUE THREAD

**Issue by tspiteri** [rust-num/num-bigint#124]
Little endian is about byte order, not word order. So the order of the bytes in the `u32` itself would be little endian or big endian depending on the platform, but the `u32` values themselves are ordered least significant first, not in little-endian order.

**Comment by cuviper** [comment]
Wikipedia's description of [endianness](https://en.wikipedia.org/wiki/Endianness) supports a broader sense:

> It can also be used more generally to refer to the internal ordering of any representation, such as the digits in a numeral system or the sections of a date. 

I would accept a PR changing to "least significant first" though, if you find that clearer.
