### ISSUE TITLE
Implement Euclidean division and modulo

### ISSUE THREAD

**Issue by betaveros** [rust-num/num-bigint#146]
I see we have floor division and the corresponding modulo operations via the Integer trait. However methods for the subtly different Euclidean division and modulo operations were added to the core Rust primitives in [RFC 2169](https://github.com/rust-lang/rfcs/blob/master/text/2169-euclidean-modulo.md) and it might be good to have them on BigInt for consistency. (If I have missed the implementation, please let me know. I am fairly new to Rust.)

**Comment by cuviper** [comment]
I'm open to it. It would be nice to sort out a common trait for this first (rust-num/num-traits#159), then `num-bigint` can implement that.
