### ISSUE TITLE
`BigUint` should impl `Add<i*>`

### ISSUE THREAD

**Issue by sollyucko** [rust-num/num-bigint#147]
Since `BigUint` implements `Sub<u*>`, it should also be able to implement `Add/Sub<i*>`. Is there any reason not to implement it? If you want, I should be able to submit a PR for this.

**Comment by sollyucko** [comment]
Also, it could probably just copy [`BigInt`'s implementations](https://docs.rs/num-bigint/0.2.6/src/num_bigint/bigint.rs.html#1082).

**Comment by cuviper** [comment]
One reason is that `Add` is an infallible operation, but `Sub` can underflow. Introducing signed operands would create more failure points, and I don't think there's much benefit. If you want signed arithmetic, you can just use `BigInt`.

**Comment by sollyucko** [comment]
True. FWIW, my use case is alternating adding and subtracting, but it's easy enough to work around this by just creating a free function modeled after `BigInt`'s `Add` implementation.
