### ISSUE TITLE
How could I get/set n-th bit of `BigInt`?

### ISSUE THREAD

**Issue by kazunetakahashi** [rust-num/num-bigint#172]
Would you do me a favor? I need some help.

I'd like to get and set $n$-th bit of `BigInt`. How could I do it in a fast way?

For example, [ramp has such methods; `bit` and `set_bit`](https://docs.rs/ramp/0.5.9/ramp/int/struct.Int.html#method.bit).

I know that I can do it by bitwise operation such as `(x >> bit) & BigInt::one() == BigInt::one()` or so on. But I need faster way.

I would be grateful if you could give me advice.

**Comment by cuviper** [comment]
I can't think of a fast way to do it with the public API right now, but we could add methods like ramp's.

Can you offer the some example motivation of what you would use this for?

**Comment by kazunetakahashi** [comment]
Thank you for your comment.

> Can you offer the some example motivation of what you would use this for?

I am trying making big prime numbers by a randomized algorithm now. This is needed for a cryptographic algorithm that I am researching on. In this method, one will try making a random integer and check if it is prime or not many times. To reduce useless attempts, `set_bit` is useful. For example, they set its 0-th bit as `1` to gain an odd number and 1023-th bit as `1` to gain such a big number for strangeness of cryptography. Similarly, `get_bit` is also good for checking prime numbers.

Other good big-integer libraries depends on C language, but yours is made of pure Rust. This is also a good point for my purpose.

**Comment by janmarthedal** [comment]
I am currently working on this, so a PR should be coming soon!

**Comment by mkaczanowski** [comment]
@janmarthedal how's the PR going? I also need this feature (the only reason why I use rug now is that function is missing)

**Comment by janmarthedal** [comment]
@mkaczanowski I have submitted a PR so I guess it is up to the project maintainers now.

**Comment by mkaczanowski** [comment]
Nice work! Thanks, @cuviper @janmarthedal

**Comment by kazunetakahashi** [comment]
@cuviper @janmarthedal Thank you so much. Today, I confirmed that my program got faster using your `bit` and `set_bit`. It helped me a lot.
