### ISSUE TITLE
Better support for bigints in generic functions

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-bigint#2]
_From @vks on March 17, 2017 17:35_

Unlike integer types that are `Copy`, for bigints it is important to avoid cloning by supporting `x + &y`, `&x + &y` etc. for all relevant operations and comparisons. The required trait bounds are cumbersome, because they need the special `for<'a>` syntax. The best way to deal with that is in my opinion what @andersk proposed:

```rust
fn extended_gcd<T: Integer>(a: T, b: T) -> GcdResult<T>
    where for<'a> &'a T: IntegerOps<T>
```

for some appropriately defined trait [`IntegerOps`](https://github.com/vks/discrete-log/blob/master/src/main.rs#L104).

This would be useful for optimizations like in #153, i.e. for generic functions like `pow`, `gcd` and `binomial`.

_Copied from original issue: rust-num/num#273_

**Comment by cuviper** [comment]
_From @vks on June 11, 2017 10:20_

I believe this was implemented in 21b520ea15a07b2197c4c6950a4996a182b56619. The functions above don't use it yet, but this would be a breaking change.

**Comment by vks** [comment]
I also think this is implemented. The only thing that seems to be left is improving `pow`, `gcd` and `binomial` to use the new traits.

**Comment by cuviper** [comment]
OK, closing.
