### ISSUE TITLE
Converting alphanumeric byte array with radix 36

### ISSUE THREAD

**Issue by rohitjoshi** [rust-num/num-bigint#238]
Converting alphanumeric string to BigUint using radix 36 and back fails. When it converts back, it is all lower case alphanumeric.

```
#[test]
    fn parse_bytes_radix36() {
        use fpe::ff1::Numeral;
        env_logger::init();
        let data = "006kZGBb".as_bytes();
        let num = BigUint::parse_bytes(data, 36).unwrap();
        trace!(
            "input:{}, BigUint::parse_bytes(36):{}",
            String::from_utf8_lossy(data),
            num
        );
        trace!(
            "num:{}, num to_str_radix(36):{}",
            num,
            //String::from_utf8_lossy(&num.to_radix_be(36)),
            num.to_str_radix(36)
        );
        assert_eq!(data, num.to_str_radix(36).as_bytes())
    }
```

[2022-03-22T19:55:16Z TRACE algorithm::tests] input:**006kZGBb**, BigUint::parse_bytes(36):398043479
[2022-03-22T19:55:16Z TRACE algorithm::tests] num:398043479, num to_str_radix(36):**6kzgbb**

thread 'algorithm::tests::parse_bytes_radix36' panicked at 'assertion failed: `(left == right)`
  left: `[48, 48, 54, 107, 90, 71, 66, 98]`,
 right: `[54, 107, 122, 103, 98, 98]`', src/algorithm.rs:938:9

**Comment by cuviper** [comment]
Yes, parsing radix-36 is a case-insensitive operation, which makes it lossy in that regard. We don't offer a choice of case when formatting back, although you could use `to_ascii_uppercase()` if desired. But any information about the case of individual input digits is completely lost.

**Comment by rohitjoshi** [comment]
Any suggestions to preserve case for individual digits? Or any other crate which supports it?

**Comment by cuviper** [comment]
I don't know of anything like that.

Maybe you can explain why you want this? If it's just to compare known values, you could normalize the other to lowercase as well, for example.

**Comment by rohitjoshi** [comment]
It is used to create a token from alphanumeric string using ff1 encryption/decryption (fpe crate). Both input and output values are case sensitive.

**Comment by cuviper** [comment]
It looks to me like FF1 needs a radix size that is greater than the number of characters in your alphabet. If upper and lower case are distinct to you, then they need to be counted separately, so `[0-9A-Za-z]` is 62 characters.

`BigUint` doesn't have string conversions for that high of a radix, but if you map the characters to numeric digits `< radix` yourself, you can use [from_radix_be](https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#method.from_radix_be). Likewise, [to_radix_be](https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#method.to_radix_be) will go back to bytes which you can then map to characters.

**Comment by rohitjoshi** [comment]
Closing the issue as case-sensitive alphanumeric requires base 62.
