### ISSUE TITLE
Base 1 support

### ISSUE THREAD

**Issue by Rudxain** [rust-num/num-bigint#246]
`parse_bytes` doesn't support a radix of 1, why is that? Unary is the easiest numeral system to parse! Just get the `len` of the `String` and call it a day. No need to validate that all chars are equal to each other (unless the user/dev wants a stricter validation)

**Comment by cuviper** [comment]
https://en.wikipedia.org/wiki/Unary_numeral_system
> However, because the value of a digit does not depend on its position, it is not a form of positional notation, and it is unclear whether it would be appropriate to say that it has a base (or "radix") of 1, as it behaves differently from all other bases.

I'll take the stance that it's not appropriate to call that a radix.

If you really want convert a unary string, you can use `BigInt::from(my_unary.len())`.

**Comment by Rudxain** [comment]
Fair enough

**Comment by Rudxain** [comment]
I realized this should be closed as "not planned"
