### ISSUE TITLE
How do I cast BigUint to u128?

### ISSUE THREAD

**Issue by andrew-sol** [rust-num/num-bigint#251]
I use `BigUint` for some calculations and the output always satisfies the `u128` range. I need to store the result as `u128`.

So far I've tried this solution:
```
let num = BigUint::from(1000u128).to_string().parse::<u128>().unwrap();
```
but it feels not optimal.

Are there other ways?

**Comment by entropidelic** [comment]
hello! BigUints satisfy the `ToPrimitive` trait from the `num_traits` crate. Using the `to_u128()` method should be enough for what you want. Here's an example
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=47b1118ed9db1f235d92e3e7a671a42e

**Comment by andrew-sol** [comment]
It works, thanks!

I will add that this approach requires adding an additional crate: https://docs.rs/num-traits/latest/num_traits/

**Comment by cuviper** [comment]
You can also use the standard `TryFrom` or `TryInto`, which are in the language prelude in the Rust 2021 edition.
