### ISSUE TITLE
Add `to_bytes_padded` or conversion to `crypto_bigint::Uint`

### ISSUE THREAD

**Issue by Plebshot** [rust-num/num-bigint#252]
Hello, I am running into issues trying to convert an arbitrarily large `BigUint` into a fixed size [`crypto_bigint::Uint`](https://docs.rs/crypto-bigint/latest/crypto_bigint/struct.UInt.html) (Specifically, I'm working with [`p384`](https://docs.rs/p384/latest/p384/) elliptic curve). To ensure the number fits into the fixed size `Uint`, I am performing modulo reduction beforehand.

A workaround I found it to use `BigUint::to_bytes_be()` and reinterpreting the bytes. However, for this I need to pad the resulting bytes to the fixed length required for  `crypto_bigint::Uint`. More specifically, the bytes have to be padded to the front of the vector. Openssl BigNums provide a [`to_vec_padded`](https://docs.rs/openssl/latest/openssl/bn/struct.BigNumRef.html#method.to_vec_padded) for this exact use case.

Would it be possible to get something similar in this crate? Alternatively an efficient way to convert from `BigUint` to `crypto_bigint::Uint` (perhaps even in place) would be amazing. 

Thanks for the time!

**Comment by cuviper** [comment]
It looks like `crypto_bigint` uses a little-endian representation itself, so I think you could efficiently use `BigUint::to_bytes_le`, then `.resize(len, 0)` for padding and pass it to `Uint::from_le_slice`.

**Comment by Plebshot** [comment]
Ah thanks, I forgot that `resize` works nicely with little endian here. I suppose the extra `resize` could end up with an extra allocation though. A direct conversion could also probably still be done faster, but understandably not worth the effort.

Anyways, this works for me at the moment. You can close the issue if you aren't interested in adding a slightly optimized `to_bytes_padded()`
