### ISSUE TITLE
`BigUint::from` isn't generic

### ISSUE THREAD

**Issue by Rudxain** [rust-num/num-bigint#255]
Apologies in advance if this has already been mentioned, I know redundancy is bad.

I don't know if these "bugs" happen in specific situations, but `rustc` can't do type inference on an int-literal passed to `BigUint::from` even though `rust-analyzer` explicitly tells me that it only accepts `u64`, so I must explicitly type the `_u64` suffix

**Comment by Rudxain** [comment]
[The `match` problem was my fault](https://doc.rust-lang.org/book/ch18-03-pattern-syntax.html). I forgot about the fact that non-literals are treated differently

**Comment by cuviper** [comment]
> even though `rust-analyzer` explicitly tells me that it only accepts `u64`

It's wrong if it's telling you *only* `u64`, because `BigUint::from` words for _all_ unsigned primitive integer types.
https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#impl-From%3Cu128%3E

When faced with an ambiguous integer literal, the compiler falls back to `i32`, which unfortunately won't work for `BigUint`.

**Comment by Rudxain** [comment]
> It's wrong if it's telling you _only_ `u64`, because `BigUint::from` words for _all_ unsigned primitive integer types. https://docs.rs/num-bigint/latest/num_bigint/struct.BigUint.html#impl-From%3Cu128%3E
> 
> When faced with an ambiguous integer literal, the compiler falls back to `i32`, which unfortunately won't work for `BigUint`.

Oooh right, I'm so dumb. I thought type inference also worked for input args, but it makes sense that it doesn't work, because params and return values must be explicitly annotated.

Thank you for the info, I'll close the issue

**Comment by cuviper** [comment]
> I thought type inference also worked for input args,

FWIW, that does work when there's only option. For example, `BigUint::from_slice(&[1, 2, 3])` will infer those to be `u32`.
