### ISSUE TITLE
Is there a reason that `Copy` isn't implemented for `BigInt` and `BigUint`

### ISSUE THREAD

**Issue by zhenfeizhang** [rust-num/num-bigint#260]
I am building some structs like 
``` rust
#[derive(Clone)]
struct MyStruct {
    foo: BigInt
}
```
and I cannot derive `Copy` for this structure.

**Comment by zhenfeizhang** [comment]
To answer my own question -- `BigUint` has a vector field, and that doesn't allow for copy. 
So what is the best way to copy `MyStruct`?

**Comment by cuviper** [comment]
I'm afraid `Clone` is the best you can do, unless you can switch to a statically-sized numeric type, without allocation.

**Comment by zhenfeizhang** [comment]
Cool. Thanks!
