### ISSUE TITLE
Whether to enable simd support？

### ISSUE THREAD

**Issue by 12915494174** [rust-num/num-bigint#262]
I am now using this library to do some large integer calculations. I need to convert the code to wasm. I find that some operations will slow down after the conversion to wasm. Is there any way to enable simd to speed up the running speed of the converted code, or to speed up the speed of the unconverted code.

**Comment by cuviper** [comment]
There isn't any explicit simd support here yet, only what the compiler (especially LLVM) may be able to optimize based on your target-cpu and target-features.

**Comment by 12915494174** [comment]
OK, thank you for your reply
