### ISSUE TITLE
to_str_radix produces odd number of digits

### ISSUE THREAD

**Issue by KuTuGu** [rust-num/num-bigint#269]
I think [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8c15db8a68e54518e4a1bc660c5c56ac) should return "0102" instead of "102".

How about supporting it by deciding on odd bits to fill leading zeros?

Glad to submit a pr to fix it.

**Comment by cuviper** [comment]
Why do you expect leading zeros? The standard library doesn't do that -- `println!("{:x}", 0x0102_u16);` prints "102". But you can get that padding with a format like `"{:04x}"`, and you can make that width "4" dynamic based on `bits()` too.

**Comment by KuTuGu** [comment]
Excuse me，I may have confused string with hex.
