### ISSUE TITLE
Build script could be replaced with const fn

### ISSUE THREAD

**Issue by Wuelle** [rust-num/num-bigint#270]
Currently, [`build.rs`](https://github.com/rust-num/num-bigint/blob/master/build.rs)  [computes a few constants](https://github.com/rust-num/num-bigint/blob/master/build.rs#L54) and stores them as rust code in a file, which is later [included by the actual source code](https://github.com/rust-num/num-bigint/blob/6f2b8e0fc218dbd0f49bebb8db2d1a771fe6bafa/src/biguint/convert.rs#L780).

This is a bit silly since the exact same thing can be accomplished in a `const`-context, without needing to parse autogenerated code or any file IO.

For example, you could use code like this:
```rs
const BASES_16: [(u16; usize); 257] = {
     // Code evaluated at compile time which returns the required array.
     // [ ... ]
};
```
If this is something that the maintainers of this project agree with, i could make a PR.

**Comment by cuviper** [comment]
I don't think there's much _advantage_ to moving this out of the build script, and there are real disadvantages to working within the limitations of `const`. The current code is simple and very little maintenance burden.

**Comment by Wuelle** [comment]
Sure. 
Just out of curiosity, what are these "real disadvantages to working within the limitations of `const`"?
The only one that comes to my mind is that for loops are not `const`, so you would need to count with `while`

**Comment by Wuelle** [comment]
Okay thanks :+1: , I'll close this for now
