### ISSUE TITLE
BigInt absolute value as a BigUint value

### ISSUE THREAD

**Issue by ghallak** [rust-num/num-bigint#275]
Is there a way to get the absolute value of a `BigInt` as a `BigUint`?

I currently do this to convert to `BigUint`:

```
BigInt::from(-5).abs().to_biguint().unwrap()
```

But I think it makes sense to have a function in the library for that.

**Comment by cuviper** [comment]
You can use [magnitude](https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html#method.magnitude) to borrow it, or [into_parts](https://docs.rs/num-bigint/latest/num_bigint/struct.BigInt.html#method.into_parts) if you want to take ownership.

**Comment by ghallak** [comment]
Thanks, that's what I'm looking for.
