### ISSUE TITLE
Add is_negative and is_non_negative

### ISSUE THREAD

**Issue by hydroper** [rust-num/num-bigint#279]
Is there a way to skip getting the `Sign` for determining negative or non-negative?

I noted also that:

- `is_negative` is private: https://github.com/rust-num/num-bigint/blob/master/src/bigint.rs#L280

I'd like both `is_negative` and a `is_non_negative` method. `is_positive` could also be public.

**Comment by cuviper** [comment]
Those are not private methods -- they are implementations of the `num_traits::Signed` trait.
