### ISSUE TITLE
Possible Incompleteness

### ISSUE THREAD

**Issue by YichiZhang0613** [rust-num/num-bigint#293]
In num-bigint/src/bigint.rs and num-bigint/src/biguint.rs, I think the code should check modulus != 0 and exponent >= 0/modulus != 0 as comments mentioned before use them to avoid possible panic.
num-bigint/src/bigint.rs
```rust
/// Panics if the exponent is negative or the modulus is zero.
    pub fn modpow(&self, exponent: &Self, modulus: &Self) -> Self {
        power::modpow(self, exponent, modulus)
    }
```
num-bigint/src/biguint.rs
```rust
/// Panics if the modulus is zero.
    pub fn modpow(&self, exponent: &Self, modulus: &Self) -> Self {
        power::modpow(self, exponent, modulus)
    }
```

**Comment by cuviper** [comment]
Those nested functions do check their conditions right away:

https://github.com/rust-num/num-bigint/blob/e9b204cf5abd91dda241a921444cce4abcc6f885/src/bigint/power.rs#L71-L79

https://github.com/rust-num/num-bigint/blob/e9b204cf5abd91dda241a921444cce4abcc6f885/src/biguint/power.rs#L134-L138

> to avoid possible panic.

How would we *avoid* the panic? These functions have no other way to communicate such an error. We could add `checked_modpow` variants that return an `Option` though.

**Comment by cuviper** [comment]
I see that you have opened a few similar issues on different projects. In general, it is not considered a problem in Rust if a function panics when documented preconditions are not met -- it means that it is always considered a bug on the caller.
