### ISSUE TITLE
Hide bigint implementation details

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-bigint#3]
_From @cuviper on January 8, 2016 6:21_

With `BigDigit` exposed in the interface, we're somewhat limited in what kind of changes we can make to the implementation.  Even just `fn new(digits: Vec<BigDigit>)` strongly implies that this storage will be directly used by the new `BigUint`.

_Copied from original issue: rust-num/num#155_

**Comment by cuviper** [comment]
_From @briansmith on January 8, 2016 22:47_

> Even just fn new(digits: Vec<BigDigit>) strongly implies that this storage will be directly used by the new BigUint.

I think that might be implied, but I don't think it is big deal if that isn't the case. You could leave `BigDigit` defined as it is currently and then use another name, e.g. `Limb` for the internal type. Then the public functions that take `BigDigit` values would just be `[deprecated]` conversion functions.

Note that `Limb` is a better name anyway, IMO. See this for the origin of the term `Limb`: https://gmplib.org/manual/Nomenclature-and-Types.html

**Comment by cuviper** [comment]
Yeah, that's true.  I think we even discussed on another issue that we could use careful transmutes and byte swaps to still reuse that storage, even when `Limb` is a different size.  So yes, we could change the implementation without actually affecting the API, then the only breaking change is to eventually remove the vestigial parts.

**Comment by cuviper** [comment]
`pub enum ParseBigIntError` is another pain point.  The way it tries to extend `ParseIntError` makes it clumsy to actually create errors, and we can't change this without breaking.  `ParseRatioError` is a better example how it should be, where the enum is hidden as a private field in a struct.

**Comment by cuviper** [comment]
It occurred to me recently that serialization is actually a breaking change too, because changes to type internals may alter the serialized format.  That's especially true when they're derived, like we're doing for `rustc_serialize`, but we should be careful even with our manual `serde` implementation.

**Comment by CAD97** [comment]
I believe this is closed by #38 now?

Is the serde-model version of `Big(U)Int` considered stable now? (I think that if so, this issue is indeed fuly resolved.) Given that changing the internal representation could inadvertently break serialization backwards-compatibility, there should probably at least be a warning comment in the source somewhere (which at a quick glance I was unable to find), since it's usually safe to go changing purely internal details, but the serde implementation effectively "leaks" the construction from base-u32.

**Comment by cuviper** [comment]
@CAD97 That's a great point about serde -- please see #39.
