### ISSUE TITLE
Add support for 128-bit primitives

### ISSUE THREAD

**Issue by cuviper** [rust-num/num-bigint#40]
Rust 1.26 is stabilizing `i128` and `u128`.  We should add support for for these, to the same extent that other primitive types are supported.  This should be a conditional feature, rather than forcing all of `num-bigint` up to the very latest compiler -- e.g. rust-num/num-traits#60 has a new feature "i128".

- [x] convert to and from 128-bit integers #44 
- [x] implement operators with 128-bit operands
- [ ] implement `BigDigit = u64` with `DoubleBigDigit = u128`
  - still conditional on new enough rustc, and probably only for specific target CPUs

**Comment by dignifiedquire** [comment]
I will likely work on `BigDigit = u64` in the next days, as I have seen significant speed increases when using this in other code.

**Comment by andresilva** [comment]
FWIW I did this on a local branch (before finding this issue) and I noticed non-negligible performance improvements at least for `modpow` which is what I was benchmarking. It would be nice if it detected the native word size to automatically pick the type for `BigDigit` (maybe using `target_pointer_width`?).

**Comment by cuviper** [comment]
How about the division benchmarks?  That's the main thing that worries me with `DoubleBigDigit = u128` -- from what I've seen, LLVM never optimizes this to x86's pseudo-128-bit `DIV` with `RDX:RAX`.  There are division tests in `benches/bigint.rs` and `benches/factorial.rs`, so I'm guessing it's those `factorial_div_*` ones where you noticed a slowdown.

I'll want to see full benchmarks before we merge anything, not just cherry-picked impressive ones, but we'll get to that in your PRs.

**Comment by cuviper** [comment]
Wild idea: It might be possible to take a hybrid approach, using `u64` and `u128` for most operations, but casting the digits down to `[u32]` (with big-endian fixups) for the raw `div_rem_digit` and `div_wide`.

**Comment by dignifiedquire** [comment]
This is the current state: https://gist.github.com/dignifiedquire/b7d442bea7bc2490bffd32ae31081f8 I have on my machine.

I am actually seeing speed ups in the division benchmarks, as far as I can tell.

I think hybrid could work, but I am not convinced it is needed/actually faster on supported architectures.

**Comment by cuviper** [comment]
Your gist link is 404 from here.

The benefits to other operations involved in the division algorithm might outweigh the slowdown I'm expecting in raw `u128` division.  The single-digit divisors in `factorial_div_*` will probably be more sensitive to that low-level performance.

**Comment by dignifiedquire** [comment]
- ah yes factorial_div are the ones with the slow down, this will need some work to figure out to ensure no regression happens there
- link should be fixed now
