### ISSUE TITLE
Please make trailing_zeros public

### ISSUE THREAD

**Issue by dignifiedquire** [rust-num/num-bigint#58]
I am working on some code that needs access to this information, and currently have no (performant) way of accessing it, as it relies on the internal `data` field which is not accessible either

**Comment by akubera** [comment]
I'd like to second this suggestion. In implementing [bigdecimal](https://github.com/akubera/bigdecimal-rs), I think counting trailing zeros could lead to some nice optimizations (an optimized method for counting *all* digits would be nice, too).

**Comment by tafia** [comment]
I would like having this public too!

**Comment by cuviper** [comment]
This was included in #62, heading for version 0.3 (#128).
