### ISSUE TITLE
Need help to use with lazy_static

### ISSUE THREAD

**Issue by dignifiedquire** [rust-num/num-bigint#59]
I have a couple of constants which I would define as such using `lazy_static!` but this fails for me

```rust
lazy_static! {
      static ref BIG_3: BigUint = BigUint::from_u64(3).unwrap();
}

// later this fails with: `no implementation for `&num_bigint::BigUint - &prime::BIG_3`
let res = my_number - &BIG_3;

// but this works, but clippy is upset that I am using `&`  but if I remove it it stops compiling
if my_number < &BIG_3 { }
```
any ideas how to work around this?

**Comment by cuviper** [comment]
Your `BIG_3` is actually a wrapper that performs the dynamic initialization. You have to dereference it to get the underlying value, and then you can take a reference to that, like `&*BIG_3`. In some cases Rust can auto-deref things, but not here.

**Comment by dignifiedquire** [comment]
Thank you, I see. Works like a charm
