### ISSUE TITLE
Use from/into instead of as, to ensure type conversions are not lossy

### ISSUE THREAD

**Issue by dignifiedquire** [rust-num/num-bigint#66]
There are quite a lot of places in the codebase (easy to see if you run `cargo clippy`) where, e.g. `val as u32` is done, instead of `u32::from(val)`. 

Clippy lint: https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#cast_lossless

**Comment by mikong** [comment]
I'm currently working on this. I'll submit a PR soon.
