### ISSUE TITLE
Add ceiling division for BigInt ?

### ISSUE THREAD

**Issue by iosmanthus** [rust-num/num-bigint#69]
In python, we can easily implement ceiling division for the integer type. 
```python
def ceildiv(a, b):
    return -(-a // b)
```
Maybe it will be more convenient if we implement a similar method for `BigInt`.
```rust
extern crate num;

use num::BigInt;
use num::Zero;

pub trait CeilDiv<RHS = Self> {
    type Output;
    fn ceildiv(&self, rhs: RHS) -> Self::Output;
}

impl CeilDiv for BigInt {
    type Output = BigInt;
    fn ceildiv(&self, rhs: Self) -> Self::Output {
        let (q, r) = (self / &rhs, self % &rhs);
        let padding = ((*self < Self::zero()) ^ (rhs > Self::zero()))
            && (r != Self::zero());
        q + Self::from(padding as i32)
    }
}

fn main() {
    assert_eq!(BigInt::from(5).ceildiv(BigInt::from(2)), BigInt::from(3));
    assert_eq!(BigInt::from(5).ceildiv(BigInt::from(-2)), BigInt::from(-2));
}
```

**Comment by cuviper** [comment]
I would most likely do this in [`num_integer::Integer`](https://docs.rs/num-integer/0.1.39/num_integer/trait.Integer.html), based on [`div_mod_floor`](https://docs.rs/num-integer/0.1.39/num_integer/trait.Integer.html#method.div_mod_floor) something like this:

```rust
    fn div_ceil(&self, other: &Self) -> Self {
        let (d, m) = self.div_mod_floor(other);
        if m.is_zero() {
            d
        } else {
            d + Self::one()
        }
    }
```

Specific implementations like `BigInt` can then override this as needed for efficiency.

I can imagine `mod_ceil` and `div_mod_ceil` too, but it may have to require `Self: Signed`, depending on how we define this modulus.  For example, [`mod_floor`](https://docs.rs/num-integer/0.1.39/num_integer/trait.Integer.html#tymethod.mod_floor) specifies:
```rust
assert!(n.div_floor(&d) * d + n.mod_floor(&d) == n)
```

To pair with `div_ceil`, either `mod_ceil` has to be `<=0`, or we could specify that equality with subtraction instead.  We should look to other languages/libraries for a precedent here.
