### ISSUE TITLE
Exponentation bug

### ISSUE THREAD

**Issue by veniamin-ilmer** [rust-num/num-bigint#74]
Running it in playground:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0d25f92071a744a754c9cc583fe8ee6b

I get the wrong answer raising any number to the power of any number.

Am I using the crate incorrectly?

**Comment by cuviper** [comment]
That's not exponentiation, it's [the bitwise XOR operator](https://doc.rust-lang.org/std/ops/trait.BitXor.html). Rust doesn't have an operator for exponentiation, but you can use [`Pow`](https://docs.rs/num-traits/0.2.6/num_traits/pow/trait.Pow.html).

**Comment by veniamin-ilmer** [comment]
I am sorry. My mistake. Closing ticket.
