### ISSUE TITLE
Doesn't compile without the std feature

### ISSUE THREAD

**Issue by est31** [rust-num/num-bigint#76]
If you disable the std feature, this crate won't compile.

Just try: 

```
git clone https://github.com/rust-num/num-bigint
cargo build --no-default-features
```

You'll get a ton of errors.

**Comment by cuviper** [comment]
Yes, that's intentional. Note that the readme says:

> The std crate feature is mandatory and enabled by default. If you depend on num-bigint with default-features = false, you must manually enable the std feature yourself. In the future, we hope to support #![no_std] with the alloc crate when std is not enabled.

**Comment by est31** [comment]
Oh, so it's done for forwards compatibility reasons (default-features = false use)... I see, this makes sense. Thanks for the explainer.
