### ISSUE TITLE
Postgres representation

### ISSUE THREAD

**Issue by elpiel** [rust-num/num-bigint#94]
Hello,
I am looking a way to use BigUint in Postgres when using rust-postgres.
I found only [1 issue in rust-postgres](https://github.com/sfackler/rust-postgres/issues/307) talking about Big numbers support, but no resolution for it.
Sadly my knowledge in the triplet Big Numbers, Postgres and Rust is not sufficient to figure out a way to do it on my own. I don't know how Big Numbers are represented, how to store them in Postgres nor my skills in Rust are good enough for that.

I will gladly try to implement the `num-bigint` for `rust-postgres` with some guidance.

**Comment by hauleth** [comment]
I think that you should ask that question on `rust-postgres` as it is highly unlikely that there will be any changes in this repository during that integration.

**Comment by elpiel** [comment]
Fair point! Totally agree. Closing the issue
