### ISSUE TITLE
Support #![no_std]

### ISSUE THREAD

**Issue by maxbla** [rust-num/num-bigint#96]
From the readme
>  In the future, we hope to support #![no_std] with the alloc crate when std is not enabled.

It was my understanding that we were holding back on this until alloc was stabilized, which happened fairly recently, in [1.28](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1280-2018-08-02)

**Comment by cuviper** [comment]
If you check the links, those stabilized `alloc` APIs were actually just for the *module* `alloc`, accessible through `core::alloc` or `std::alloc`, and these are just the raw allocator APIs.

The `alloc` crate will finally be stabilized in 1.36 (https://github.com/rust-lang/rust/pull/59675/), which will include the `alloc::vec::Vec` we need to easily support `num-bigint`.

**Comment by maxbla** [comment]
Hm, I didn't realize what exactly we needed when writing this issue, but `alloc::vec::Vec` makes more sense. 1.36 will probably be released around the end of June. We could just keep this issue open until then.

**Comment by cuviper** [comment]
Yeah, that's fine. I'm even going to self-assign this, because I have a WIP branch around here somewhere... :)

**Comment by 0ndorio** [comment]
As 1.36 was release last week it would now be possible to attack that issue again. Can I somehow help to make it happen?

**Comment by meltinglava** [comment]
Tried this. Looks like [`std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html) trait does not have a alloc or core counterpart. Do not know how to solve that. Do you want me to make an WIP PR?

**Comment by cuviper** [comment]
Yeah, `Error` will need to a `cfg` for `std` only.

As mentioned, I do have a WIP branch myself, just need to get around to it. I will try to do this soon...

**Comment by cuviper** [comment]
See draft PR #101, if you'd like to test.

**Comment by SOF3** [comment]
Why is this issue not closed, since feature std is already in Cargo.toml?

**Comment by cuviper** [comment]
Ah, I just forgot to link from the PR to close this.
